In [1]:
import numpy as np
from numpy import zeros, ones, eye
import matplotlib.pyplot as plt
# import tensorflow as tf

In [2]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]], dtype=np.float32)

AND = np.array([[-1],[-1],[-1],[1]], dtype=np.float32) # also tf.float32 implicitly
OR = np.array([[-1],[1],[1],[1]], dtype=np.float32) # also tf.float32 implicitly
NOR = np.array([[1],[-1],[-1],[-1]], dtype=np.float32) # also tf.float32 implicitly
NAND = np.array([[1],[1],[1],[-1]], dtype=np.float32) # also tf.float32 implicitly
XOR = np.array([[-1],[1],[1],[-1]], dtype=np.float32) # also tf.float32 implicitly
RHO = np.array([[.0001],[.001],[.01],[.01],[.1],[1]])

# J = lambda y, w, x: y*x*w
# S = lambda x: 1/(1 + np.exp(-x))
def cost(y,x,w):
    J = y*x*w
    print(y*x*w)
    return J

In [96]:
w_k = np.random.randn(1,3)

# no_of_iterations_to_converge = []
cost = 0
for i in range(100000):
    for k in range(len(X)):
        X[k,0:3] = X[k,0:3]*AND[k,0]
#         y_b = X[k,:] @ w_k
#         y_b = np.round(y_b)
#         err = AND[k,:] - y_b
        
        if w_k @ X[k,:] <= 0:
            w_k = w_k + RHO[-3]*X[k,:]

In [97]:
(X@w_k.reshape(3,1))

array([[0.01466578],
       [0.02476923],
       [0.01374728],
       [0.02568773]])

In [91]:
X[0,:].reshape(3,1)

array([[-0.],
       [-0.],
       [ 1.]], dtype=float32)

In [92]:
w_k

array([[-0.21614206,  0.83137091,  0.83590772]])

In [41]:
X[0,0:2]*AND[k,0]

array([-0., -0.], dtype=float32)

In [58]:
np.random.randn(3,1)

array([[ 0.09625091],
       [-0.03778416],
       [-1.42532483]])

In [68]:
X[0,:].shape

(3,)

In [73]:
X.shape

(4, 3)

In [74]:
w_k.shape

(1, 3)

In [81]:
len(X)

4