In [1]:
import numpy as np
# from scipy.special import softmax
# from numpy import zeros, ones, eye
import matplotlib.pyplot as plt
# import tensorflow as tf

In [2]:
X = np.array([[0,0],\
              [0,1],\
              [1,0],\
              [1,1]], dtype=np.float32)#1 appended in the last column is the bias

t = { #dictionary for getting both the target logic values and the correlated string 
    # binary labels to represent the probabilities of 1 or 0 (first column is 0, 2nd 1)
    "AND": np.array([[1, 0], [1, 0], [1, 0], [0, 1]], dtype=np.float32),
    "NAND": np.array([[0, 1], [0, 1], [0, 1], [1, 0]], dtype=np.float32),
    "OR": np.array([[1, 0], [0, 1], [0, 1], [0, 1]], dtype=np.float32),
    "NOR": np.array([[0, 1], [1, 0], [1, 0], [1, 0]], dtype=np.float32),
    "XOR": np.array([[1, 0], [0, 1], [0, 1], [1, 0]], dtype=np.float32) 
}

#learning reates
RHO = np.array([.0001,.001,.01,.01,.1,1], dtype=np.float32)

In [59]:
def forward_prop_A(W1, b1, W2, b2, X):
    A1 = (X @ W1 + b1)[0]
    Z1 = logistic_sigmoid(A1) 
    A2 = (Z1 @ W2 + b2)[0]
    Y = softmax(A2)
    return A1, A2, Y


def logistic_sigmoid(x, derivative=0):
    sigm = 1/(1 + np.exp(-x))
    if derivative:
        return sigm * (1. - sigm)
    return sigm

def softmax(X, derivative=0):
#     for i in range(len(X[:,1])):
#         S[:,i] = np.exp(X) / np.sum(np.exp(X))
    for i in range(len(X[:,1])):
        S[i,:] = np.exp(X[i,:]) / np.sum(np.exp(X[:,i]))
        
    ans = np.zeros(X.shape)
    if derivative:
        ans[0] = -S[0]*S[1]
        
        for i in range()
        ans[1] = S[0]*(1 - S[1])
        return ans
    return S

def backprop_A(W2, A1, A2, X, Y, t):
    grad_mid_layer = (t-Y) @ -softmax(A2, derivative=1).T * logistic_sigmoid(A1, derivative=1) @ W2 @ X.T
    grad_output = (t-Y) @ -softmax(A2, derivative=1).T * logistic_sigmoid(A1, derivative=0) 
    
    grad_output = grad_output @ np.eye(grad_output.shape[0],M=2)
    return grad_mid_layer, grad_output

def forward_prop_A2(W1, b1, W2, b2, X):
    A1 = (X @ W1 + b1)[0]
#     Z1 = sigmoid(A1) 
    A2 = (A1 @ W2 + b2)[0]
    Y = softmax(A2)
    return A1, A2, Y

def backprop_A2(W2, A1, A2, X, Y, t):
    grad_mid_layer = (t-Y) @ -softmax(A2, derivative=1).T 
    grad_mid_layer = grad_mid_layer @ X.T
    grad_mid_layer = grad_mid_layer @ np.eye(A1.shape[0]) @ W2
    
    grad_output = (t-Y) @ -softmax(A2, derivative=1).T
    grad_output = grad_output @ A1
    grad_output = grad_output @ np.eye(grad_output.shape[0],M=2)
    
    
    return grad_mid_layer, grad_output

In [60]:
NO_UNITS_L1 = 2
W1 = np.random.randn(2,NO_UNITS_L1)
b1 = np.zeros((1,NO_UNITS_L1))
W2 = np.random.randn(NO_UNITS_L1,2) # 2 outputs, P(0) and P(1)
b2 = np.zeros((1,2))

In [61]:
rho = .01
batch = 1

if batch:
    for i in range(30_000):
            A1, A2, Y = forward_prop_A2(W1, b1, W2, b2, X)
            grad_mid_layer, grad_output = backprop_A2(W2, A1, A2, X, Y, t["AND"])

            W1 = W1 - rho*grad_mid_layer
            W2 = W2 - rho*grad_output.T
            b1 = b1 - rho*np.mean(grad_mid_layer)
            b2 = b2 - rho*np.mean(grad_output)
else:
    for i in range(10_000):
        for j in range(len(X[:,1])):
            A1, A2, Y = forward_prop_A2(W1, b1, W2, b2, X[j,:])
            grad_mid_layer, grad_output = backprop_A2(W2, A1, A2, X[j,:], Y, t["AND"][j,:])

            W1 = W1 - rho*grad_mid_layer
            W2 = W2 - rho*grad_output.T
            b1 = b1 - rho*np.mean(grad_mid_layer)
            b2 = b2 - rho*np.mean(grad_output)

IndexError: too many indices for array

In [16]:
test = 3
A1, A2, Y = forward_prop_A(W1, b1, W2, b2, X[test,:])
# print("X: " + str(X[test,:]))
print("t: " + str(t["AND"][test,:]))
print("Y: " + str(Y))

t: [0. 1.]
Y: [0.51623245 0.48376755]


In [26]:
np.eye(A1.shape[0])

array([[1., 0.],
       [0., 1.]])

In [27]:
(t["AND"][test,:]-Y) @ -softmax(A2, derivative=1).T# * np.eye(A1.shape[0]) @ W2 @ X[test,:].T

-0.25

In [34]:
W2 @ X.T

array([[ 0.        ,  0.99643249, -1.00417655, -0.00774406],
       [ 0.        , -0.43952952,  0.11198779, -0.32754172]])

In [39]:
np.eye(A1.shape[0])

array([[1., 0.],
       [0., 1.]])